catlin/urls.py
from django.urls import path
from . import views

app_name = 'catlin'
urlpatterns = [
    path("", views.index, name='index'),
    path("about/", views.about, name='about'),
    path("<int:category_id>/", views.category, name='category'),
    path("<int:category_id>/all-links/", views.category_pages, name='category_pages'),
    path("user/<str:username>/", views.users_categories, name='users_categories'),
    path("new-link-group/", views.add_category, name='add_category'),
    path("<int:category_id>/add-link/", views.add_page, name='add_page'),
    path("<int:category_id>/update/", views.update_category, name='update_category'),
    path("<int:category_id>/delete/", views.delete_category, name='delete_category'),
    path("<int:category_id>/delete-linkgroup-verified/", views.delete_category_verified, name='delete_category_verified'),
    path("add-comment/", views.add_comment, name='add_comment'),
    path("page/<int:page_id>/", views.goto_page, name='goto_page'),
    path("link/<int:page_id>/delete/", views.delete_page, name='delete_page'),
    path("link/<int:page_id>/delete-link-verify/", views.delete_page_verify, name='delete_page_verify'),
    path("linkgroup-search/", views.search, name='search'),
    path("link-search/", views.search_pages, name='search_pages'),
    path("like_category/", views.like_category, name='like_category'),
    path("like_page/", views.like_page, name='like_page'),
    path("like_comment/", views.like_comment, name='like_comment'),
    path("see_replies/", views.see_replies, name='see_replies'),
    path("delete-linkgroup-successfull/", views.del_cat_successfull, name='del_cat_successfull'),
    path("latest-linkgroups/", views.latest_categories, name='latest_categories'),
    path("most-liked-linkgroups/", views.most_liked_categories, name='most_liked_categories'),
    path("users-results/", views.search_users, name='search_users'),
    path("search-users/", views.search_users_page, name='search_users_page'),
]

linkspot/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('linkgroup/', include('catlin.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
        name = 'password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

catlin/forms.py
from django import forms

class AddCategoryForm(forms.Form):
    title = forms.CharField(label='Title', max_length=100)
    summary = forms.CharField(label='Summary', widget=forms.Textarea ,max_length=500)

class AddPageForm(forms.Form):
    title = forms.CharField(label='Title', max_length=100)
    summary = forms.CharField(label='Summary', widget=forms.Textarea ,max_length=500)
    url = forms.URLField(label='URL', max_length=100)

class AddCommentForm(forms.Form):
    content = forms.CharField(
        label = '',
        widget=forms.Textarea(attrs = {
            'id':'new-comment',
            'placeholder':'Post your thoughts'
            }
    ))

catlin/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.core.paginator import Paginator
from catlin.models import (
    Category, Page, Comment, LikePage, LikeComment, LikeCategory
)
from users.models import Profile
from .forms import AddCategoryForm, AddPageForm, AddCommentForm
from catlin.search.mysearch import compare_strings


def like_my_model(my_request, entity_model, like_model):
    """
    like_model = LikePage, LikeComment, LikeCategory
    entity_model = Page, Comment, Category
    AJAX post request must contain: entity_id, liketype('L' or 'D')
    returns dict {likes, dislikes}
    """
    entity_id = None
    like_type = None
    not_like_type = 'D'
    like_type_count = 0
    not_like_type_count = 0
    likes = 0
    dislikes = 0
    user = Profile.objects.get(user=my_request.user)
    if my_request.method == "POST":
        entity_id = my_request.POST['entity_id']
        like_type = my_request.POST['liketype']
        if like_type == 'D':
            not_like_type = 'L'
    if entity_id:
        entity_obj = entity_model.objects.get(id=int(entity_id))
        if entity_obj:
            # likes = entity_obj.like_count #
            # dislikes = entity_obj.dislike_count #
            try:
                like_obj = like_model.objects.get(entity=entity_obj, user=user)
                if like_obj.type == like_type:
                    like_obj.delete()
                    like_type_count -= 1
                elif like_obj.type == not_like_type:
                    like_obj.type = like_type
                    like_obj.save()
                    like_type_count += 1
                    not_like_type_count -= 1
            except like_model.DoesNotExist:
                like_obj = like_model(entity=entity_obj, user=user, type=like_type)
                like_obj.save()
                like_type_count += 1
            if like_type == 'L':
                likes += like_type_count
                dislikes += not_like_type_count
            elif like_type == 'D':
                likes += not_like_type_count
                dislikes += like_type_count
            entity_obj.like_count += likes
            entity_obj.dislike_count += dislikes
            entity_obj.save()
            if entity_model == Category and entity_obj.user:
                entity_obj.user.like_count += likes
                entity_obj.user.dislike_count += dislikes
                entity_obj.user.save()
    return {'likes': entity_obj.like_count, 'dislikes': entity_obj.dislike_count}


def get_search_categories(search_string, max_results=25, threshold=0):
    search_result_cats = []
    cat_score_list = []
    cat_id_list = []
    category_list = Category.objects.all()

    # Filling cat_score_list, cat_id_list
    for category in category_list:
        cat_score_list.append(compare_strings(search_string, category.title))
        cat_id_list.append(category.id)

    # Collecting matched ids
    for i in range(0, max_results):
        max1 = max(cat_score_list)
        if max1 > threshold:
            index = cat_score_list.index(max1)
            search_result_cats.append(category_list.get(id=cat_id_list[index]))
            cat_score_list[index] = 0
    return search_result_cats


def get_search_pages(search_string, max_results=25, threshold=0):
    search_result_pages = []
    page_score_list = []
    page_id_list = []
    page_list = Page.objects.all()
    # Filling page_score_list, page_id_list
    for page in page_list:
        page_score_list.append(compare_strings(search_string, page.title))
        page_id_list.append(page.id)

    # Collecting matched ids
    for i in range(0, max_results):
        max1 = max(page_score_list)
        if max1 > threshold:
            index = page_score_list.index(max1)
            search_result_pages.append(page_list.get(id=page_id_list[index]))
            page_score_list[index] = 0
    return search_result_pages


def get_search_users(search_string, max_results=25, threshold=0):
    search_result_users = []
    user_score_list = []
    user_id_list = []
    user_list = Profile.objects.all()
    # Filling page_score_list, page_id_list
    for user in user_list:
        user_score_list.append(compare_strings(
            search_string, user.user.username))
        user_id_list.append(user.id)

    # Collecting matched ids
    for i in range(0, max_results):
        max1 = max(user_score_list)
        if max1 > threshold:
            index = user_score_list.index(max1)
            search_result_users.append(user_list.get(id=user_id_list[index]))
            user_score_list[index] = 0
    return search_result_users


# Create your views here.
def index(request):
    category_list = Category.objects.all()
    paginator = Paginator(category_list, 5)
    page_no = request.GET.get('page')
    categories = paginator.get_page(page_no)
    context = {
        'categories': categories,
        'heading': 'All Linkgroups'
    }
    return render(request, 'catlin/category_list.html', context)


def users_categories(request, username):
    try:
        author = Profile.objects.get(user__username=username)
    except Profile.DoesNotExist:
        return render(request, 'catlin/not_exist.html', {'type': 'user'})
    category_list = Category.objects.filter(user=author)
    paginator = Paginator(category_list, 5)
    page_no = request.GET.get('page')
    categories = paginator.get_page(page_no)
    context = {
        'categories': categories,
        'heading': 'Linkgroups of ' + username,
    }
    return render(request, 'catlin/category_list.html', context)


def category(request, category_id):
    comment_index = 0  # some request object
    no_of_comments = 5  # fixed see more comments
    try:
        category = Category.objects.get(id=category_id)
    except Category.DoesNotExist:
        return render(request, 'catlin/not_exist.html', {'type': 'category'})
    category.views += 1
    category.save()
    pages = Page.objects.filter(category=category).order_by('-like_count')[:5]
    main_comments = Comment.objects.filter(category=category, depth='M').order_by(
        '-last_modified')[comment_index:comment_index+no_of_comments]
    main_comment_form = AddCommentForm()
    context = {
        'category': category,
        'pages': pages,
        'comments': main_comments,
        'main_comment_form': main_comment_form,
    }
    return render(request, 'catlin/category.html', context)


def category_pages(request, category_id):
    try:
        category = Category.objects.get(id=category_id)
    except Category.DoesNotExist:
        return render(request, 'catlin/not_exist.html', {'type': 'category'})
    page_list = Page.objects.filter(category=category)
    paginator = Paginator(page_list, 5)
    page_no = request.GET.get('page')
    pages = paginator.get_page(page_no)
    context = {
        'pages': pages,
        'heading': category.title,
        'type': 'category pages',
    }
    return render(request, 'catlin/page_list.html', context)


@login_required
def add_category(request):
    if request.method == 'POST':
        form = AddCategoryForm(request.POST)
        if form.is_valid():
            user = Profile.objects.get(user=request.user)
            cat = Category(
                title=form.cleaned_data['title'],
                summary=form.cleaned_data['summary'],
                user=user,)
            user.category_count += 1
            user.save()
            cat.save()
            return HttpResponseRedirect(
                reverse('catlin:update_category', args=[cat.id]))
    else:
        form = AddCategoryForm()
    context = {
        'form': form,
    }
    return render(request, 'catlin/add_category.html', context)


@login_required
def add_page(request, category_id):
    try:
        category = Category.objects.get(id=category_id)
    except Category.DoesNotExist:
        return render(request, 'catlin/not_exist.html', {'type': 'category'})
    if request.method == 'POST' and request.user == category.user.user:
        form = AddPageForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            page = Page(
                title=form.cleaned_data['title'],
                summary=form.cleaned_data['summary'],
                url=form.cleaned_data['url'],
                category=category
            )
            page.save()
            category.page_count += 1
            category.save()
            return HttpResponseRedirect(reverse('catlin:update_category', args=[category_id]))
    elif request.user != category.user.user:
        return render(request, 'catlin/not_authorised.html', {})
    form = AddPageForm()
    context = {
        'category_id': category_id,
        'form': form,
    }
    return render(request, 'catlin/add_page.html', context)


@login_required
def delete_page(request, page_id):
    try:
        page = Page.objects.get(id=page_id)
    except Page.DoesNotExist:
        return render(request, 'catlin/not_exist.html', {'type': 'page'})
    user = page.category.user
    if user.user == request.user:
        return render(request, 'catlin/verify_page_delete.html', {'page': page})
    return render(request, 'catlin/not_authorised.html', {})


@login_required
def delete_page_verify(request, page_id):
    try:
        page = Page.objects.get(id=page_id)
    except Page.DoesNotExist:
        return render(request, 'catlin/not_exist.html', {'type': 'page'})
    category = page.category
    user = category.user
    if user.user == request.user and request.method == 'POST':
        page.delete()
        category.page_count -= 1
        category.save()
        messages.success(request, "The link was deleted successfully.")
        return redirect('catlin:update_category', category_id=category.id)

catlin/templates/base.html
<!DOCTYPE html>
<html>
<head>
  {% load static %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Bootstrap CSS -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
  <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static '/catlin/basestyle.css' %}">
  <title>LinkSpot</title>


</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'catlin:index' %}">LinkSpot</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'catlin:index' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'catlin:about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'catlin:add_category' %}">New Linkgroup</a>
              <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
              <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
              <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
              <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
  </header>
  <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Useful Links</h3>
            <p class='text-muted'>Welcome to LinkSpot
              <ul class="list-group">
                <a href="{% url 'catlin:latest_categories' %}" class="list-group-item list-group-item-light">Latest Linkgroups</a>
                <a href="{% url 'catlin:most_liked_categories' %}" class="list-group-item list-group-item-light">Most Liked Linkgroups</a>
                <a href="{% url 'catlin:search_users_page' %}" class="list-group-item list-group-item-light">Search Users</a>
              </ul>
            </p>
          </div>
        </div>
      </div>
  </main>
  <script src="{% static '/js/jquery-3.3.1.js' %}"></script>
  <script src="{% static '/js/catlin-jquery.js' %}"></script>
  <script src="{% static '/js/catlin-ajax.js' %}"></script>
  <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> -->
</body>
</html>