catlin/urls.py
from django.urls import path
from . import views

app_name = 'catlin'
urlpatterns = [
    path("", views.index, name='index'),
    path("about/", views.about, name='about'),
    path("<int:category_id>/", views.category, name='category'),
    path("<int:category_id>/all-links/", views.category_pages, name='category_pages'),
    path("user/<str:username>/", views.users_categories, name='users_categories'),
    path("new-link-group/", views.add_category, name='add_category'),
    path("<int:category_id>/add-link/", views.add_page, name='add_page'),
    path("<int:category_id>/update/", views.update_category, name='update_category'),
    path("<int:category_id>/delete/", views.delete_category, name='delete_category'),
    path("<int:category_id>/delete-linkgroup-verified/", views.delete_category_verified, name='delete_category_verified'),
    path("add-comment/", views.add_comment, name='add_comment'),
    path("page/<int:page_id>/", views.goto_page, name='goto_page'),
    path("link/<int:page_id>/delete/", views.delete_page, name='delete_page'),
    path("link/<int:page_id>/delete-link-verify/", views.delete_page_verify, name='delete_page_verify'),
    path("linkgroup-search/", views.search, name='search'),
    path("link-search/", views.search_pages, name='search_pages'),
    path("like_category/", views.like_category, name='like_category'),
    path("like_page/", views.like_page, name='like_page'),
    path("like_comment/", views.like_comment, name='like_comment'),
    path("see_replies/", views.see_replies, name='see_replies'),
    path("delete-linkgroup-successfull/", views.del_cat_successfull, name='del_cat_successfull'),
    path("latest-linkgroups/", views.latest_categories, name='latest_categories'),
    path("most-liked-linkgroups/", views.most_liked_categories, name='most_liked_categories'),
    path("users-results/", views.search_users, name='search_users'),
    path("search-users/", views.search_users_page, name='search_users_page'),
]

linkspot/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('linkgroup/', include('catlin.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
        name = 'password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

catlin/forms.py
from django import forms

class AddCategoryForm(forms.Form):
    title = forms.CharField(label='Title', max_length=100)
    summary = forms.CharField(label='Summary', widget=forms.Textarea ,max_length=500)

class AddPageForm(forms.Form):
    title = forms.CharField(label='Title', max_length=100)
    summary = forms.CharField(label='Summary', widget=forms.Textarea ,max_length=500)
    url = forms.URLField(label='URL', max_length=100)

class AddCommentForm(forms.Form):
    content = forms.CharField(
        label = '',
        widget=forms.Textarea(attrs = {
            'id':'new-comment',
            'placeholder':'Post your thoughts'
            }
    ))

catlin/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.core.paginator import Paginator
from catlin.models import (
    Category, Page, Comment, LikePage, LikeComment, LikeCategory
)
from users.models import Profile
from .forms import AddCategoryForm, AddPageForm, AddCommentForm
from catlin.search.mysearch import compare_strings


def like_my_model(my_request, entity_model, like_model):
    """
    like_model = LikePage, LikeComment, LikeCategory
    entity_model = Page, Comment, Category
    AJAX post request must contain: entity_id, liketype('L' or 'D')
    returns dict {likes, dislikes}
    """
    entity_id = None
    like_type = None
    not_like_type = 'D'
    like_type_count = 0
    not_like_type_count = 0
    likes = 0
    dislikes = 0
    user = Profile.objects.get(user=my_request.user)
    if my_request.method == "POST":
        entity_id = my_request.POST['entity_id']
        like_type = my_request.POST['liketype']
        if like_type == 'D':
            not_like_type = 'L'
    if entity_id:
        entity_obj = entity_model.objects.get(id=int(entity_id))
        if entity_obj:
            # likes = entity_obj.like_count #
            # dislikes = entity_obj.dislike_count #
            try:
                like_obj = like_model.objects.get(entity=entity_obj, user=user)
                if like_obj.type == like_type:
                    like_obj.delete()
                    like_type_count -= 1
                elif like_obj.type == not_like_type:
                    like_obj.type = like_type
                    like_obj.save()
                    like_type_count += 1
                    not_like_type_count -= 1
            except like_model.DoesNotExist:
                like_obj = like_model(entity=entity_obj, user=user, type=like_type)
                like_obj.save()
                like_type_count += 1
            if like_type == 'L':
                likes += like_type_count
                dislikes += not_like_type_count
            elif like_type == 'D':
                likes += not_like_type_count
                dislikes += like_type_count
            entity_obj.like_count += likes
            entity_obj.dislike_count += dislikes
            entity_obj.save()
            if entity_model == Category and entity_obj.user:
                entity_obj.user.like_count += likes
                entity_obj.user.dislike_count += dislikes
                entity_obj.user.save()
    return {'likes': entity_obj.like_count, 'dislikes': entity_obj.dislike_count}


def get_search_categories(search_string, max_results=25, threshold=0):
    search_result_cats = []
    cat_score_list = []
    cat_id_list = []
    category_list = Category.objects.all()

    # Filling cat_score_list, cat_id_list
    for category in category_list:
        cat_score_list.append(compare_strings(search_string, category.title))
        cat_id_list.append(category.id)

    # Collecting matched ids
    for i in range(0, max_results):
        max1 = max(cat_score_list)
        if max1 > threshold:
            index = cat_score_list.index(max1)
            search_result_cats.append(category_list.get(id=cat_id_list[index]))
            cat_score_list[index] = 0
    return search_result_cats


def get_search_pages(search_string, max_results=25, threshold=0):
    search_result_pages = []
    page_score_list = []
    page_id_list = []
    page_list = Page.objects.all()
    # Filling page_score_list, page_id_list
    for page in page_list:
        page_score_list.append(compare_strings(search_string, page.title))
        page_id_list.append(page.id)

    # Collecting matched ids
    for i in range(0, max_results):
        max1 = max(page_score_list)
        if max1 > threshold:
            index = page_score_list.index(max1)
            search_result_pages.append(page_list.get(id=page_id_list[index]))
            page_score_list[index] = 0
    return search_result_pages


def get_search_users(search_string, max_results=25, threshold=0):
    search_result_users = []
    user_score_list = []
    user_id_list = []
    user_list = Profile.objects.all()
    # Filling page_score_list, page_id_list
    for user in user_list:
        user_score_list.append(compare_strings(
            search_string, user.user.username))
        user_id_list.append(user.id)

    # Collecting matched ids
    for i in range(0, max_results):
        max1 = max(user_score_list)
        if max1 > threshold:
            index = user_score_list.index(max1)
            search_result_users.append(user_list.get(id=user_id_list[index]))
            user_score_list[index] = 0
    return search_result_users


# Create your views here.
def index(request):
    category_list = Category.objects.all()
    paginator = Paginator(category_list, 5)
    page_no = request.GET.get('page')
    categories = paginator.get_page(page_no)
    context = {
        'categories': categories,
        'heading': 'All Linkgroups'
    }
    return render(request, 'catlin/category_list.html', context)


def users_categories(request, username):
    try:
        author = Profile.objects.get(user__username=username)
    except Profile.DoesNotExist:
        return render(request, 'catlin/not_exist.html', {'type': 'user'})
    category_list = Category.objects.filter(user=author)
    paginator = Paginator(category_list, 5)
    page_no = request.GET.get('page')
    categories = paginator.get_page(page_no)
    context = {
        'categories': categories,
        'heading': 'Linkgroups of ' + username,
    }
    return render(request, 'catlin/category_list.html', context)


def category(request, category_id):
    comment_index = 0  # some request object
    no_of_comments = 5  # fixed see more comments
    try:
        category = Category.objects.get(id=category_id)
    except Category.DoesNotExist:
        return render(request, 'catlin/not_exist.html', {'type': 'category'})
    category.views += 1
    category.save()
    pages = Page.objects.filter(category=category).order_by('-like_count')[:5]
    main_comments = Comment.objects.filter(category=category, depth='M').order_by(
        '-last_modified')[comment_index:comment_index+no_of_comments]
    main_comment_form = AddCommentForm()
    context = {
        'category': category,
        'pages': pages,
        'comments': main_comments,
        'main_comment_form': main_comment_form,
    }
    return render(request, 'catlin/category.html', context)


def category_pages(request, category_id):
    try:
        category = Category.objects.get(id=category_id)
    except Category.DoesNotExist:
        return render(request, 'catlin/not_exist.html', {'type': 'category'})
    page_list = Page.objects.filter(category=category)
    paginator = Paginator(page_list, 5)
    page_no = request.GET.get('page')
    pages = paginator.get_page(page_no)
    context = {
        'pages': pages,
        'heading': category.title,
        'type': 'category pages',
    }
    return render(request, 'catlin/page_list.html', context)


@login_required
def add_category(request):
    if request.method == 'POST':
        form = AddCategoryForm(request.POST)
        if form.is_valid():
            user = Profile.objects.get(user=request.user)
            cat = Category(
                title=form.cleaned_data['title'],
                summary=form.cleaned_data['summary'],
                user=user,)
            user.category_count += 1
            user.save()
            cat.save()
            return HttpResponseRedirect(
                reverse('catlin:update_category', args=[cat.id]))
    else:
        form = AddCategoryForm()
    context = {
        'form': form,
    }
    return render(request, 'catlin/add_category.html', context)


@login_required
def add_page(request, category_id):
    try:
        category = Category.objects.get(id=category_id)
    except Category.DoesNotExist:
        return render(request, 'catlin/not_exist.html', {'type': 'category'})
    if request.method == 'POST' and request.user == category.user.user:
        form = AddPageForm(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            page = Page(
                title=form.cleaned_data['title'],
                summary=form.cleaned_data['summary'],
                url=form.cleaned_data['url'],
                category=category
            )
            page.save()
            category.page_count += 1
            category.save()
            return HttpResponseRedirect(reverse('catlin:update_category', args=[category_id]))
    elif request.user != category.user.user:
        return render(request, 'catlin/not_authorised.html', {})
    form = AddPageForm()
    context = {
        'category_id': category_id,
        'form': form,
    }
    return render(request, 'catlin/add_page.html', context)


@login_required
def delete_page(request, page_id):
    try:
        page = Page.objects.get(id=page_id)
    except Page.DoesNotExist:
        return render(request, 'catlin/not_exist.html', {'type': 'page'})
    user = page.category.user
    if user.user == request.user:
        return render(request, 'catlin/verify_page_delete.html', {'page': page})
    return render(request, 'catlin/not_authorised.html', {})


@login_required
def delete_page_verify(request, page_id):
    try:
        page = Page.objects.get(id=page_id)
    except Page.DoesNotExist:
        return render(request, 'catlin/not_exist.html', {'type': 'page'})
    category = page.category
    user = category.user
    if user.user == request.user and request.method == 'POST':
        page.delete()
        category.page_count -= 1
        category.save()
        messages.success(request, "The link was deleted successfully.")
        return redirect('catlin:update_category', category_id=category.id)

catlin/templates/catlin/category.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<!-- CATEGORY SECTION -->
<div class="content-section">
  {% if request.user == category.user.user %}
  <a class="btn btn-outline-warning btn-sm mb-4" href="{% url 'catlin:update_category' category.id %}">Update</a>
  {% endif %}
<article class="media content-section">
  <img class="rounded-circle article-img" src="{{category.user.image.url}}"/>
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{% url 'catlin:users_categories' category.user.user.username %}">{{category.user.user.username}}</a>
      <small class="text-muted">{{category.last_modified|date:"D d, Y"}}</small>
    </div>
    <h2 class="article-title">{{category.title}}</h2>
    <p class="article-content">{{category.summary}}</p>
    <strong id="like_counts">{{ category.like_count }}</strong>
    <button class="btn btn-info btn-sm" id="likes" data-catid="{{category.id}}" type="button">
    Like
    </button>
    <strong id="dislike_counts">{{ category.dislike_count }}</strong>
    <button class="btn btn-secondary btn-sm" id="dislikes" data-catid="{{category.id}}" type="button">
    Dislike
    </button>

  </div>
</article>

<!-- PAGES SECTION -->
<h3 class="border-bottom pb-2">Links
  <small>({{category.page_count}})</small>
</h3>
{% if pages %}
{% for page in pages %}
<p class="float-right">
  <strong id="like_page_count{{page.id}}">{{ page.like_count }}</strong>
  <button class="btn btn-info btn-sm like_page" id="like_page{{page.id}}" data-pageid="{{page.id}}" type="button">
  Like
  </button>
  <strong id="dislike_page_count{{page.id}}">{{ page.dislike_count }}</strong>
  <button class="btn btn-secondary btn-sm dislike_page" id="dislike_page{{page.id}}" data-pageid="{{page.id}}" type="button">
  Dislike
  </button>
</p>
<a href="{% url 'catlin:goto_page' page.id %}">{{page.title}}</a> <span>({{page.views}} view{{page.views|pluralize}})</span>
 <p class="pt-2 pb-4">{{page.summary}}</p>
{% endfor %}
<div class="row justify-content-center">
  <a href="{% url 'catlin:category_pages' category.id %}" class="btn btn-link">See All</a>
</div>

{% else %}
<strong>No links in this linkgroup yet.</strong>
{% endif %}
</div>

<!--COMMENT SECTION-->
<div class="content-section">
  <h3 class="border-bottom pb-2">Comments <small>({{category.comment_count}})</small></h3>
<form action="" method="post" id="post-comment-form">{% csrf_token %}
  <fieldset class="form-group">
      {{main_comment_form|crispy}}
  </fieldset>
  <div class="form-group">
    <input class="btn btn-outline-info btn-sm" id='comment-btn' type="submit" name="PostComment" value="Post Comment" data-catid="{{category.id}}">
  </div>
</form>

<div id="comments" data-catid="{{category.id}}">
{% for comment in comments %}
<div class="comment{{comment.id}}">
  <div class="article-metadata">
    <a class="mr-2" href="#">{{comment.user.user.username}}</a>
    <small class="text-muted">{{comment.last_modified|date:"D d, Y"}}</small>
</div>
<p>{{comment.content}}</p>

<p>
<strong id="like_comment_count{{comment.id}}">{{ comment.like_count }}</strong>
<button class="btn btn-info btn-sm like_comment" id="like_comment{{comment.id}}" data-commentid="{{comment.id}}" type="button">
Like
</button>
<strong class="ml-2" id="dislike_comment_count{{comment.id}}">{{ comment.dislike_count }}</strong>
<button class="btn btn-secondary btn-sm dislike_comment" id="dislike_comment{{comment.id}}" data-commentid="{{comment.id}}" type="button">
Dislike
</button>
</p>

<!-- QUERIED NESTED COMMENTS -->
<a class='text-primary see-comment-reply-btn' type="button" data-commentid='{{comment.id}}'>Reply</a>
<a id='see-replies-btn{{comment.id}}' class='text-primary ml-4 see-replies-btn' type="button" data-mcommentid={{comment.id}}>{{comment.comment_count}} Replies</a>
<div class='post-comment-reply' id='form-post-comment-reply{{comment.id}}' style="margin-left:30px; display:none;">
    <textarea name="content" placeholder="Post your thoughts" id="new-comment{{comment.id}}" style="width:100%"></textarea>
    <input class='btn btn-outline-info btn-sm comment-reply-btn' type='submit' name='PostComment' value='Post' data-commentid='{{comment.id}}'>
</div>
<div class='nested-comments' id='div_see_replies{{comment.id}}' style="margin-left:30px; display:none;"></div>

</div>
<br/>
{% endfor %}
</div>

</div>
{% endblock %}

catlin/templates/catlin/category_list.html
{% extends 'base.html' %}
{% block content %}
<div class="content-section">

    <form class="mb-4" action="{% url 'catlin:search' %}" method="GET">
        <input class="col-md-9" type="text" name="search_string" value="" placeholder="Linkspot Search">
        <input class="btn btn-outline-info" type="submit" value="Search">
    </form>

    <h2 class="border-bottom mb-4">{{heading}}</h2>
    {% if type == 'category search' %}
      <form action="{% url 'catlin:search_pages' %}" method="GET">
        <input type="hidden" name="search_string" value="{{heading}}">
        <button class="btn btn-link" type='submit'>Search links for <strong>'{{heading}}'</strong></button>
      </form>
    {% endif %}

    {% if categories %}
    {% for category in categories %}
      <article class="media content-section">
        <img class="rounded-circle article-img" src="{{category.user.image.url}}"/>
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="{% url 'catlin:users_categories' category.user.user.username %}">{{category.user.user.username}}</a>
            <small class="text-muted">{{category.last_modified|date:"D d, Y"}}</small>
            <small class="text-muted float-right">{{category.page_count}} link{{category.page_count|pluralize}}</small>
          </div>
          <h2><a href="{% url 'catlin:category' category.id %}" class="article-title">{{category.title}}</a></h2>
          <p class="article-content">{{category.summary}}</p>
        </div>
      </article>
    {% endfor %}

      <div class="btn-group">
          {% if categories.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{categories.previous_page_number}}">Previous</a>
          {% endif %}
          {% for num in categories.paginator.page_range %}
            {% if categories.number == num %}
              <a class="btn btn-info mb-4" href="?page={{num}}">{{num}}</a>
            {% elif num > categories.number|add:'-3' and num < categories.number|add:'3' %}
              <a class="btn btn-outline-info mb-4" href="?page={{num}}">{{num}}</a>
            {% endif %}
          {% endfor %}
          {% if categories.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{categories.next_page_number}}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{categories.paginator.num_pages}}">Last</a>
          {% endif %}
      </div>

    {% else %}
      <p><strong>No linkgroups matched your query.</strong></p>
    {% endif %}

</div>


{% endblock %}

catlin/templates/catlin/page_list.html
{% extends 'base.html' %}
{% block content %}
<div class="content-section">

    <form class="mb-4" action="{% url 'catlin:search' %}" method="GET">
        <input class="col-md-9" type="text" name="search_string" value="" placeholder="Linkspot Search">
        <input class="btn btn-outline-info" type="submit" value="Search">
    </form>

    <h2 class="border-bottom mb-4">{{heading}}</h2>
    {% if type == 'page search' %}
      <form action="{% url 'catlin:search' %}" method="GET">
        <input type="hidden" name="search_string" value="{{heading}}">
        <button class="btn btn-link" type='submit'>Search linkgroups for <strong>'{{heading}}'</strong></button>
      </form>
    {% endif %}

    {% if pages %}
      {% for page in pages %}
        <p class="float-right">
          <strong id="like_page_count{{page.id}}">{{ page.like_count }}</strong>
          <button class="btn btn-info btn-sm like_page" id="like_page{{page.id}}" data-pageid="{{page.id}}" type="button">
          Like
          </button>
          <strong id="dislike_page_count{{page.id}}">{{ page.dislike_count }}</strong>
          <button class="btn btn-secondary btn-sm dislike_page" id="dislike_page{{page.id}}" data-pageid="{{page.id}}" type="button">
          Dislike
          </button>
        </p>
        <a href="{% url 'catlin:goto_page' page.id %}">{{page.title}}</a><span> ({{page.views}} view{{page.views|pluralize}})</span>
        <p>{{page.summary}}</p>
        <p><strong>Linkgroup: </strong><a href="{% url 'catlin:category' page.category.id %}">{{page.category.title}}</a></p>
      {% endfor %}

      <div class="btn-group">
          {% if pages.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?search_string={{heading}}&page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?search_string={{heading}}&page={{pages.previous_page_number}}">Previous</a>
          {% endif %}
          {% for num in pages.paginator.page_range %}
            {% if pages.number == num %}
              <a class="btn btn-info mb-4" href="?search_string={{heading}}&page={{num}}">{{num}}</a>
            {% elif num > pages.number|add:'-3' and num < pages.number|add:'3' %}
              <a class="btn btn-outline-info mb-4" href="?search_string={{heading}}&page={{num}}">{{num}}</a>
            {% endif %}
          {% endfor %}
          {% if pages.has_next %}
            <a class="btn btn-outline-info mb-4" href="?search_string={{heading}}&page={{pages.next_page_number}}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?search_string={{heading}}&page={{pages.paginator.num_pages}}">Last</a>
          {% endif %}
      </div>

    {% else %}
      <p><strong>No links matched your query.</strong></p>
    {% endif %}

</div>


{% endblock %}

catlin/templates/catlin/search.html
{% extends 'base.html' %}
{% block content %}
<div class="content-section">

    <form class="mb-4" action="{% url 'catlin:search' %}" method="GET">
        <input class="col-md-9" type="text" name="search_string" value="" placeholder="Linkspot Search">
        <input class="btn btn-outline-info" type="submit" value="Search">
    </form>

<h2>Search Results</h2>
<div class="search-categories">
  <h3>Link Groups</h3>
  {% if search_result_cats %}
  {% for category in search_result_cats %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{category.user.image.url}}"/>
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{% url 'catlin:users_categories' category.user.user.username %}">{{category.user.user.username}}</a>
        <small class="text-muted">{{category.last_modified|date:"D d, Y"}}</small>
        <small class="text-muted float-right">{{category.page_count}} link{{category.page_count|pluralize}}</small>
      </div>
      <h2><a href="{% url 'catlin:category' category.id %}" class="article-title">{{category.title}}</a></h2>
      <p class="article-content">{{category.summary}}</p>
    </div>
  </article>
  {% endfor %}
  {% else %}
  <strong>No linkgroups matched with your search.</strong>
  {% endif %}
</div>

<div class="search-pages">
  <h3>Pages</h3>
  {% if search_result_pages %}
  {% for page in search_result_pages %}
    <a href="{% url 'catlin:goto_page' page.id %}">{{page.title}}</a><span> ({{page.views}} view{{page.views|pluralize}})</span>
    <p>{{page.summary}}</p>
    <p><strong>Category: </strong><a href="{% url 'catlin:category' page.category.id %}">{{page.category.title}}</a></p>
  {% endfor %}
  {% else %}
  <strong>No pages matched with your search.</strong>
  {% endif %}
</div>
</div>
{% endblock %}

catlin/templates/catlin/update_category.html
{% extends 'base.html' %}

{% block content %}
<div class="content-section">
<a class="btn btn-outline-info btn-sm mb-4" href="{% url 'catlin:add_page' category.id %}">Add new Link</a>
<a class="btn btn-outline-danger btn-sm mb-4" href="{% url 'catlin:delete_category' category.id %}">Delete This Linkgroup</a>
<a class="btn btn-outline-success btn-sm mb-4" href="{% url 'catlin:category' category.id %}">Preview</a>

<article class="media content-section">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="#">{{category.user.user.username}}</a>
      <small class="text-muted">{{category.last_modified|date:"D d, Y"}}</small>
    </div>
    <h2 class="article-title">{{category.title}}</h2>
    <p class="article-content">{{category.summary}}</p>
  </div>
</article>

<h3 class="border-bottom">Links <small>({{category.page_count}})</small></h3>
  {% if pages %}
  {% for page in pages %}
    <a href="{% url 'catlin:goto_page' page.id %}">{{page.title}}</a> <span>({{page.views}} view{{page.views|pluralize}})</span>
    <a href="{% url 'catlin:delete_page' page.id %}" class="btn btn-danger btn-sm float-right">X</a>
    <p class="text-secondary">
    <strong id="like_page_count{{page.id}}">Likes:</strong> {{ page.like_count }}
    <strong id="dislike_page_count{{page.id}}">Dislikes:</strong> {{ page.dislike_count }}
  </p><p>
    <strong class="text-body">Summary: </strong>{{page.summary}}</p>
  {% endfor %}
  {% else %}
  <strong>Currently, no links in this linkgroup.</strong>
  {% endif %}

</div>
{% endblock %}

catlin/templates/catlin/user_list.html
{% extends 'base.html' %}
{% block content %}
<div class="content-section">

    <form class="mb-4" action="{% url 'catlin:search_users' %}" method="GET">
        <input class="col-md-9" type="text" name="search_string" value="" placeholder="Search Users">
        <input class="btn btn-outline-info" type="submit" value="Search">
    </form>

    <h2 class="border-bottom mb-4">{{heading}}</h2>
    {% if users %}
    {% for user in users %}
      <article class="media content-section">
        <img class="rounded-circle article-img" src="{{user.image.url}}"/>
        <div class="media-body">
          <div class="">
            <a class="mr-2" href="{% url 'catlin:users_categories' user.user.username %}">{{user.user.username}}</a>
            <small class="text-muted float-right">Likes: {{user.like_count}}</small>
             <small class="text-muted float-right mr-2">Dislikes: {{user.dislike_count}}</small>
          </div>
          <small class="text-muted">Linkgroups: {{user.category_count}}</small>
        </div>
      </article>
    {% endfor %}

      <div class="btn-group">
          {% if users.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{users.previous_page_number}}">Previous</a>
          {% endif %}
          {% for num in users.paginator.page_range %}
            {% if users.number == num %}
              <a class="btn btn-info mb-4" href="?page={{num}}">{{num}}</a>
            {% elif num > users.number|add:'-3' and num < users.number|add:'3' %}
              <a class="btn btn-outline-info mb-4" href="?page={{num}}">{{num}}</a>
            {% endif %}
          {% endfor %}
          {% if users.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{users.next_page_number}}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{users.paginator.num_pages}}">Last</a>
          {% endif %}
      </div>

    {% else %}
      <p><strong>No user matched your query.</strong></p>
    {% endif %}

</div>


{% endblock %}